simplytest_messages.settings:
  type: config_object
  label: 'Simplytest Messages settings'
  mapping:
    enable:
      type: boolean
      label: 'Show the message block'
    title:
      type: label
      label: 'Title'
    icon:
      type: sequence
      label: 'Icon'
      sequence:
        type: integer
        label: 'File ID'
    body:
      type: text_format
      label: 'Body'
