docker-compose-yaml: docker-compose.yml
environment_variables:
  git_sha: "true"
project: simplytestme-website

tasks:
  pre-rollout:
    - run:
        command: env
        name: env variables
        service: cli
  post-rollout:
    - run:
        command: |
          if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
              php vendor/bin/drush si simplytest --existing-config --account-pass=admin --yes
          fi
        name: If this is a pull request, install the database.
        service: cli
    - run:
        name: drush updb
        command: php vendor/bin/drush deploy
        service: cli
    - run:
        command: php scripts/github/deployment.php
        name: Push a deployment and success status
        service: cli
environments:
  prod:
    routes:
      - nginx:
          - simplytest.me:
              insecure: Redirect
              tls-acme: "true"
          - www.simplytest.me:
              insecure: Redirect
              tls-acme: "true"
    cronjobs:
      - name: drush cron
        schedule: "*/20 * * * *"
        command: drush cron
        service: cli
      - name: simplytest_projects_project_refresher
        schedule: "*/5 * * * *"
        command: drush queue:run simplytest_projects_project_refresher --items-limit 15
        service: cli
  main:
    routes:
      - nginx:
          - beta.simplytest.me:
              insecure: Redirect
              tls-acme: "true"
          - dev.simplytest.me:
              insecure: Redirect
              tls-acme: "true"
    cronjobs:
      - name: drush cron
        schedule: "*/20 * * * *"
        command: drush cron
        service: cli
      - name: simplytest_projects_project_refresher
        schedule: "*/5 * * * *"
        command: drush queue:run simplytest_projects_project_refresher --items-limit 15
        service: cli
