name: simplytestme
recipe: lagoon
config:
  flavor: drupal
  build:
    - COMPOSER_PROCESS_TIMEOUT=600 composer install

services:
  cli:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'https://simplytestme.lndo.site/'

tooling:
  compile:
    description: Compile the SimplyTest theme
    service: cli
    dir: /app
    cmd: composer compile

  install:
    description: Install dependencies
    service: cli
    dir: /app
    env:
      COMPOSER_PROCESS_TIMEOUT: 600
    cmd: composer install

  phpunit:
    service: cli
    cmd: vendor/bin/phpunit

  phpcs:
    service: cli
    cmd: vendor/bin/phpcs

  si:
    description: Install and configure the SimplyTest Drupal profile
    service: cli
    dir: /app
    cmd: drush si simplytest --existing-config --account-pass=admin --yes

  test:
    description: Run PHPUnit tests
    service: cli
    dir: /app
    cmd: composer tests

  xdebug-on:
    description: Enable Xdebug
    service: php
    user: root
    env:
      XDEBUG_ENABLE: true
    cmd:
      - /lagoon/entrypoints/60-php-xdebug.sh && kill -USR2 $(pgrep -o php-fpm)
      - echo "Xdebug is ON" && echo

  xdebug-off:
    description: Disable Xdebug
    service: php
    user: root
    env:
      XD_INI: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    cmd:
      # Revert the changes made by the Lagoon Xdebug entrypoints script
      - sed -i '/^xdebug.remote_host\|^$/d; s/^;*/;/g' $XD_INI && kill -USR2 $(pgrep -o php-fpm)
      - echo "Xdebug is OFF" && echo
