<?php declare(strict_types=1);

use Drupal\simplytest_projects\CoreVersionManager;
use Drupal\simplytest_projects\Entity\SimplytestProject;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function simplytest_projects_simplytest_project_insert(SimplytestProject $project) {
  $project_version_manager = \Drupal::getContainer()->get('simplytest_projects.project_version_manager');
  assert($project_version_manager !== NULL);
  $project_version_manager->updateData($project->getShortname());
}

/**
 * Implements hook_cron().
 */
function simplytest_projects_cron() {
  $core_version_manager = \Drupal::service('simplytest_projects.core_version_manager');
  assert($core_version_manager instanceof CoreVersionManager);
  $core_version_manager->updateData(7);
  $core_version_manager->updateData(8);
  $core_version_manager->updateData(9);

  $project_storage = \Drupal::entityTypeManager()->getStorage('simplytest_project');
  $query = $project_storage->getQuery()
    ->accessCheck(FALSE)
    ->condition('timestamp', strtotime('-4 hour'), '<')
    ->range(0, 50);
  $project_ids = $query->execute();

  $queue = \Drupal::queue('simplytest_projects_project_refresher');
  foreach ($project_ids as $project_id) {
    $queue->createItem($project_id);
  }


}
